### ISSUE TITLE
3D FloorPlan to HA

### ISSUE THREAD

**Issue by Nauman3S** [pkozul/ha-floorplan#87]
Start working on adding a 3D Floor Plan to HA.

**Comment by ChrisJohns-me** [comment]
I’ve started a project looking to achieve this called HA Diorama: https://github.com/ChrisJohns-me/ha-diorama
I’ve only just begun, but if anyone would like to help, let me know.

**Comment by aviel08** [comment]
> I’ve started a project looking to achieve this called HA Diorama: https://github.com/ChrisJohns-me/ha-diorama
> I’ve only just begun, but if anyone would like to help, let me know.

Hey I'd like to help in any way I can. I've been doing some tests with threejs.

**Comment by ChrisJohns-me** [comment]
I'd love the help, because I'm not sure if I'm able to tackle this alone.
I've created a Kanban board of tasks and potential tasks to be completed: https://github.com/ChrisJohns-me/ha-diorama/projects
I've also created a [Discord channel](https://discord.gg/mTYQD88) where we can chat about development.

Feel free to fork and submit pull requests; especially since we're only beginning! 😅

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
