### ISSUE TITLE
HTML custom panels have been deprecated

### ISSUE THREAD

**Issue by RoldyBuffalo** [pkozul/ha-floorplan#99]
Logger: homeassistant.components.panel_custom
Source: components/panel_custom/__init__.py:118
Integration: Custom Panel (documentation, issues)
First occurred: 12:02:44 PM (1 occurrences)
Last logged: 12:02:44 PM

What can I do to help? It seems floorplan html panels have been deprecated.

**Comment by djryan012** [comment]
Also curious if this is going to affect my setup since I prefer custom panel vs lovelace floorplan.

**Comment by RoldyBuffalo** [comment]
If I understand correctly, the custom panel, and state cards will both become non-functional in the next main-line update.

**Comment by markbooth73** [comment]
No, This is new since 0.113.0, I also get the 

Log Details (WARNING)
Logger: homeassistant.components.panel_custom
Source: components/panel_custom/__init__.py:205
Integration: Custom Panel (documentation, issues)
First occurred: 10:06:54 (1 occurrences)
Last logged: 10:06:54

HTML custom panels have been deprecated

AND

Log Details (WARNING)
Logger: homeassistant.components.frontend
Source: helpers/config_validation.py:709
Integration: Home Assistant Frontend (documentation, issues)
First occurred: 10:06:52 (1 occurrences)
Last logged: 10:06:52

The 'extra_html_url' option is deprecated, please remove it from your configuration. This option will become invalid in version 0.115
Home Assistant is starting, not everything will be available until it is finished.

**Comment by RoldyBuffalo** [comment]
I've been watching this breaking change since the day it popped up for me 3 weeks ago, but go on.

They are changing the html custom panel and card into a javascript card, much more reliable and fast. However, this requires quite a few changes in the code, minor ones, for any custom components that use the html panel feature. I have 4 different panels, well, had 4 different panels that were throwing this error. The error you're seeing is only an extension of the same breaking change, this breaking change has been around since .112, they know it will screw up a lot and are trying to give ample time to adjust. Most of the custom components that use html panels that I know of have already updated to fit this paradigm.

See this change log: [panel_custom: Allow ES5+latest build, deprecate html #36464](https://github.com/home-assistant/core/pull/36464)

In perspective, this change log is from .112 base, we have gone through .112.x and are now on .113.x, and we have until .115 to get it fixed.

I'm sure the owner knows, but small potatos. Not going to argue over it.

**Comment by RoldyBuffalo** [comment]
On the very very bottom of the release notes, not even worth highlighting apparently. 

![image](https://user-images.githubusercontent.com/58420778/88275339-d8a9db00-cca2-11ea-849e-a32a85f27b03.png)

**Comment by djryan012** [comment]
I use floorplan on my wall tablet for. It would be good to know if this custom component is planning on being updated or deprecated. I unfortunately do not have the code skill to help contribute to getting floorplan up to date.  @pkozul

**Comment by dashony** [comment]
watching this as well, floorplan is how I look over my whole house. Would have been nice for home assistant to recommend something else whilst deprecating this.

**Comment by djryan012** [comment]
It looks like this version of floorplan will be Deprecated with HA 0.115. [Lovelace-Floorplan](https://github.com/pkozul/lovelace-floorplan) does not include html so should at least transition to that veriosn of floorplan. On the other hand using the [Picture Elements Card](https://www.home-assistant.io/lovelace/picture-elements/) for HA Lovelace is basically the same thing which I am trying to get up and running before I upgrade to HA 0.115 once its released.

If you havent seen these yet. Here is a video tutorial showing use of the Picture element cards by [JuanMTech](https://youtu.be/LsFUwqb-6As) and if you havent seen [Luke Vink's](https://github.com/lukevink/hass-config-lajv) over the top version.

**Comment by RoldyBuffalo** [comment]
> It looks like this version of floorplan will be Deprecated with HA 0.115. [Lovelace-Floorplan](https://github.com/pkozul/lovelace-floorplan) does not include html so should at least transition to that veriosn of floorplan. On the other hand using the [Picture Elements Card](https://www.home-assistant.io/lovelace/picture-elements/) for HA Lovelace is basically the same thing which I am trying to get up and running before I upgrade to HA 0.115 once its released.
> 
> If you havent seen these yet. Here is a video tutorial showing use of the Picture element cards by [JuanMTech](https://youtu.be/LsFUwqb-6As) and if you havent seen [Luke Vink's](https://github.com/lukevink/hass-config-lajv) over the top version.

You do realize those two versions of floorplan are in congruence right? One is the custom panel, one is a lovelace card. Both using the same features. But go on.

**Comment by djryan012** [comment]
@RoldyBuffalo I realize that both the original floorplan and Lovelace floorplan are almost identical except for the use of the HTML file in panel format. I also read that you opened this issue willing to help update if you could. My wall tablet runs on this project as a main interface but since it has no traction since 2018 and it seems like it will not work as of 0.115 I was offering suggestions for anyone else who will find it might not work anymore. I like the simplicity of floorplan as someone who is not strong in coding and doesnt have to add custom header and other code to modify and make a simple floorplan.

**Comment by lorerave85** [comment]
Hi,
please read my post:
https://community.home-assistant.io/t/floorplan-disapear-from-custom-panel-after-update-to-v0-115/227800/13

repo with FIX:
https://github.com/lorerave85/ha-floorplan-v2

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
